### ISSUE TITLE
Guild Functionality

### ISSUE THREAD

**Issue by unpluggedsam** [neopixeldev/hypixel-api-java#43]
The `HypixelGuild` currently has a few skeleton methods to retrieve information about itself. It needs for the rest of the methods to be added to it and for them to be filled out with a `JSONObject`. Also, a discussion should be had if it needs a `RequestFactory` being passed into it's constructor or just a `JSONObject`.

**Comment by Nopock** [comment]
> The `HypixelGuild` currently has a few skeleton methods to retrieve information about itself. It needs for the rest of the methods to be added to it and for them to be filled out with a `JSONObject`. Also, a discussion should be had if it needs a `RequestFactory` being passed into it's constructor or just a `JSONObject`.

I can get started on guilds this weekend, I think JSONObject should be fine unless we require anything else but I can't think of it off the top of my head. 💯
