### ISSUE TITLE
Handling Asynchronous Data Retrieval

### ISSUE THREAD

**Issue by unpluggedsam** [neopixeldev/hypixel-api-java#85]
In an ideal world, retrieving data asynchronously in Java would be as simple as returning a `Callback` with a given type. In Javascript, it is in the same realm of simplicity. Unfortunately, Java is more complicated. It requires `CompletableFuture`'s and providing `Callback` functions within those objects. 

But it gets worse. Currently, on the branch experimenting with asynchronous data retrieval, the `RequestFactory` `send()` method returns a `CompletableFuture<JSONObject>`. Hypixel Proxy Objects (HPO), such as `HypixelPlayer`, or `HypixelGuild`, use a `RequestController` which depends on the `RequestFactory` to retrieve `JSONObject`'s. This would be fine, except when instantiating those objects they instantiate a `JSONObject` field. That means the methods in those objects can only be called once the `JSONObject` field is instantiated. 

My current theory is that no methods inside the HPO should return a `CompletableFuture`. Instead, a static factory method inside of them should return a `CompletableFuture` with the type of object it is. 

Obviously this is still open to suggestions. By having a method that returns a `CompletableFuture` within the HPO it may block the thread.

**Comment by NotInsertIGN** [comment]
How would a method that returns a `CompletableFuture` inside of a proxy object block the main thread?

**Comment by unpluggedsam** [comment]
Development of async has stopped because I can't figure it out.

**Comment by Mqlvin** [comment]
> Development of async has stopped because I can't figure it out.

I'll ask InsertIGN if they have time tonight - we can do a little discussion about how we should implement it.

**Comment by unpluggedsam** [comment]
> > Development of async has stopped because I can't figure it out.
> 
> 
> 
> I'll ask InsertIGN if they have time tonight - we can do a little discussion about how we should implement it.
> 
> 

That's fine, I can show you guys a bunch of uncommitted attempts I've got on my home computer.
